#baseurl: /jekyll-infinite
paginate: 10
plugins: [jekyll-paginate] 
title: wikipajak.org
im-logo: tiger.png

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author:  "diskusipajak"
      author-avatar: "/assets/png/logo.jpg"

sass:
    load_paths:
        - _sass

google-site-verification: halo

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", ".sass-cache"]